server:
  port: 8116
# 设置Mapper接口所对应的XML文件位置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.121.196.50:3306/weilai_wisark_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: wisark@2025
  data:
    redis:
      port: 6379
      host: 101.35.16.42
      database: 1
      password: wisark@2025
  ai:
    openai:
      api-key: sk-2a789f715c914f108ea52b05d583918a
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7
          max-tokens: 500
          # 设置惩罚值
          frequency-penalty: 0.7
  config:
    import:
      - nacos:weilai-wisark-ai.yaml

  application:
    # 该name属性和值，必须与nacos中配置的Data ID一致
    name: weilai-wisark-ai
  # nacos注册
  cloud:
    nacos:
      # 数据库连接、业务参数
      discovery:
        group: DEFAULT_GROUP
        server-addr: 47.121.196.50:8848
      config:
        server-addr: 47.121.196.50:8848
        file-extension: yaml # 文件后缀名
        group: DEFAULT_GROUP
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs/weilai-wisark-ai
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
# swagger配置
swagger:
  title: "ai服务接口"
  desc: "ai相关内容"
  version: "1.0.0"
  external-desc: 外部文档
  external-url: #
logging:
  level:
    com.weilai.ai: debug
    # spring ai advisor  日志
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: debug