server:
  port: 8118
spring:
  servlet:
    multipart:
      # 设置文件的最大值和整个请求的最大值
      max-file-size: 10MB
      max-request-size: 20MB
  # 邮箱服务
  mail:
    host: smtp.163.com
    port: 465
    password: FOAPSFOUQBZBYMXN
    username: wkldzwq@163.com
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          enable: true
          from: wkldzwq@163.com
          ssl:
            enable: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
  config:
    import:
      - nacos:weilai-wisark-user.yaml
  application:
    # 该name属性和值，必须与nacos中配置的Data ID一致
    name: weilai-wisark-user
  # nacos注册
  cloud:
    sentinel :
      transport:
        dashboard: http://82.156.115.174:8090
      http-method-specify: true
    nacos:
      # 数据库连接、业务参数
      discovery:
        group: DEFAULT_GROUP
        server-addr: 47.121.196.50:8848
      config:
        server-addr: 47.121.196.50:8848
        file-extension: yaml # 文件后缀名
        group: DEFAULT_GROUP
springdoc:
  api-docs:
    enabled: true # 开启OpenApi接口
    path: /v3/api-docs/weilai-wisark-user # 自定义路径，默认为 "/v3/api-docs"
  swagger-ui:
    enabled: true # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启
    path: /swagger-ui/index.html # 自定义路径，默认为"/swagger-ui/index.html"
# swagger配置
swagger:
  title: "用户服务接口"
  desc: "登录，注册和鉴权"
  version: "1.0.0"
  external-desc: 外部文档
  external-url: #
logging:
  level:
    com.weilai.user: debug

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 43200
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  token-prefix: Bearer
  jwt-secret-key: hfdhfjl;dhslkndsklndlsakjnfvd.a;slkdf';ldksf;

wechat:
  # appId
  app-id: wxbc71f8cdd77d23aa
  # 授权后重定向的回调链接地址
  redirect-uri: https://6eedcf93.r23.cpolar.top/wechat/callback
  # 返回类型
  response-type: code
  # snsapi_base snsapi_userinfo
  scope: snsapi_login
  appsecret: 7dc394b0cf8fd4bdb12f7b1950eb5f33
  token: 123456
